version: '3.8'

services:
  linklike-toolbox:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: linklike-toolbox
    volumes:
      - ./cache:/app/cache
      - ./masterdata:/app/masterdata
      - ./assets:/app/assets
      - ./config:/app/config:ro
    environment:
      - RUST_LOG=info
      - RUST_BACKTRACE=1
    network_mode: "bridge"
    restart: unless-stopped
    
  linklike-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    container_name: linklike-dev
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    environment:
      - RUST_LOG=debug
      - RUST_BACKTRACE=full
    network_mode: "bridge"
    profiles:
      - dev

volumes:
  cargo-cache:
  target-cache: