[package]
name = "LinkLike_Core"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = "1.1.1"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
reqwest = { version = "0.11", features = ["blocking", "rustls-tls"] }
scraper = "0.18"
regex = "1"